#!/bin/bash

ncell=7
counter=1
drname=0.3
while [  $counter -le $ncell ]; do
    cd $drname
         mpirun -np 24 /home/padma/vasp.5.4.4/bin/vasp_std
         
    cd ../
    (( counter=$counter+1 ))
    drname=$(awk -v drname="$drname" 'BEGIN{printf "%.1f", drname+0.1}')
done





